CREATE TABLE kitaplar (
    kitap_id SERIAL PRIMARY KEY,
    baslik VARCHAR(255) NOT NULL,
    yazar VARCHAR(255) NOT NULL,
    yayin_yili INT,
    tur VARCHAR(100)
);
INSERT INTO kitaplar (baslik, yazar, yayin_yili, tur)
VALUES ('Sefiller', 'Victor Hugo', 1862, 'Klasik'),
       ('Bülbülü Öldürmek', 'Harper Lee', 1960, 'Roman'),
       ('Dönüşüm', 'Franz Kafka', 1915, 'Novella'),
       ('İnce Memed', 'Yaşar Kemal', 1955, 'Roman'),
       ('Anna Karenina', 'Lev Tolstoy', 1877, 'Roman'),
       ('Yeraltından Notlar', 'Fyodor Dostoyevski', 1864, 'Novella'),
       ('Moby Dick', 'Herman Melville', 1851, 'Roman'),
       ('Don Kişot', 'Miguel de Cervantes', 1605, 'Roman'),
       ('Savaş ve Barış', 'Lev Tolstoy', 1869, 'Klasik'),
       ('Karamazov Kardeşler', 'Fyodor Dostoyevski', 1880, 'Roman'),
       ('Zaman Makinesi', 'H.G. Wells', 1895, 'Bilimkurgu'),
       ('Frankenstein', 'Mary Shelley', 1818, 'Korku'),
       ('Uğultulu Tepeler', 'Emily Brontë', 1847, 'Roman'),
       ('Hayvan Çiftliği', 'George Orwell', 1945, 'Distopya'),
       ('Cesur Yeni Dünya', 'Aldous Huxley', 1932, 'Distopya');

SELECT * FROM kitaplar;

INSERT INTO kitaplar (baslik, yazar, yayin_yili, tur)
VALUES('Yüzüklerin Efendisi', 'J.R.R. Tolkien', 1954, 'Fantastik'),
('Harry Potter ve Felsefe Taşı', 'J.K. Rowling', 1997, 'Fantastik'),
('Alacakaranlık', 'Stephenie Meyer', 2005, 'Fantastik'),
('Drakula', 'Bram Stoker', 1897, 'Korku'),
('Ateşten Gömlek', 'Halide Edip Adıvar', 1923, 'Roman'),
('Silahlara Veda', 'Ernest Hemingway', 1929, 'Roman'),
('Küçük Prens', 'Antoine de Saint-Exupéry', 1943, 'Çocuk'),
('Beyaz Kale', 'Orhan Pamuk', 1985, 'Roman'),
('Martin Eden', 'Jack London', 1909, 'Roman'),
('Oliver Twist', 'Charles Dickens', 1837, 'Roman'),
('Monte Kristo Kontu', 'Alexandre Dumas', 1844, 'Klasik'),
('Babalar ve Oğullar', 'Ivan Turgenyev', 1862, 'Roman'),
('Binbir Gece Masalları', 'Anonim', 1706, 'Masal'),
('Germinal', 'Émile Zola', 1885, 'Roman'),
('Madam Bovary', 'Gustave Flaubert', 1857, 'Roman'),
('Jane Eyre', 'Charlotte Brontë', 1847, 'Roman'),
('Büyük Umutlar', 'Charles Dickens', 1861, 'Roman'),
('Notre Dame’ın Kamburu', 'Victor Hugo', 1831, 'Roman'),
('Çavdar Tarlasında Çocuklar', 'J.D. Salinger', 1951, 'Roman'),
('Beyaz Zambaklar Ülkesinde', 'Grigory Petrov', 1923, 'Roman'),
('Bir İdam Mahkumunun Son Günü', 'Victor Hugo', 1829, 'Roman'),
('Lolita', 'Vladimir Nabokov', 1955, 'Roman'),
('Kızıl ve Kara', 'Stendhal', 1830, 'Roman'),
('Yabancı', 'Albert Camus', 1942, 'Roman'),
('Denemeler', 'Michel de Montaigne', 1580, 'Felsefe'),
('Divina Commedia', 'Dante Alighieri', 1320, 'Şiir'),
('Alice Harikalar Diyarında', 'Lewis Carroll', 1865, 'Çocuk'),
('Göçebe', 'Stephenie Meyer', 2008, 'Bilimkurgu'),
('Aganta Burina Burinata', 'Halikarnas Balıkçısı', 1945, 'Roman'),
('Mülksüzler', 'Ursula K. Le Guin', 1974, 'Bilimkurgu'),
('Amerikan Tanrıları', 'Neil Gaiman', 2001, 'Fantastik'),
('Suç ve Ceza', 'Fyodor Dostoyevski', 1866, 'Klasik'),
('Dune', 'Frank Herbert', 1965, 'Bilimkurgu'),
('Bülbülü Öldürmek', 'Harper Lee', 1960, 'Roman'),
('Gazap Üzümleri', 'John Steinbeck', 1939, 'Roman'),
('Çılgın Kalabalıktan Uzak', 'Thomas Hardy', 1874, 'Roman'),
('Büyük Gatsby', 'F. Scott Fitzgerald', 1925, 'Roman');